# Generated by Django 5.2.5 on 2025-09-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_attendancerecord_last_updated_student_lecture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
